config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  
  root to: 'toppages#index'
  
  resources :users, only: [:create, :show, :update, :destroy, :edit]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :status, presence: true, length: {maximum: 10}
  validates :user_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :tasks
  
  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email]
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログイン完了'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログイン失敗'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :show, :update, :destroy]
  
  def index
    @tasks = Task.all
  end
  
  
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    
    if @task.save
      flash[:success] = "タスクが正常に生成されました"
      redirect_to @task
    else
      flash.now[:danger] = "タスクが正常に生成されませんでした"
      render :new
    end
  end
  
  
  def new
    @task = Task.new
  end
  
  
  def edit
  end


  def show
  end
  
  
  def update
    
    if @task.update(task_params)
      flash[:success] = "正常更新"
      redirect_to @task
    else
      flash.now[:danger] = "更新失敗"
      render :edit
    end
  end
  
  
  def destroy
    @task.destroy
    
    flash[:success] = "正常に削除されました　"
    redirect_to root_url
  end
  
  private
  
  def set_task
    @task = Task.find(params[:id])
  end
  
  # Strong Params
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @tasks = Task.where(user_id: current_user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :update]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました'
      redirect_to @user
    else
      flash.now[:success] = '登録失敗'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '更新失敗'
      render :edit
    end
  end

  def destroy

  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
  <%= message %>
  </div>
<% end %>

app/views/layouts/_user_form.html.erb
    <%= form_for(:session, url: login_path) do |f| %>
      <div class='form-group'>
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class:'form-control' %>
      </div>
      
      <div clas='form-group'>
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Log in', class: 'btn btn-primary btn-block' %>
      
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
      #margin_s {margin-bottom: 20px; }
    </style>
  </head>

  <body>
    <header>
      <nav class='navbar navbar-inverse navbar-static-top'>
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          
          <a class="navbar-brand" href="/">TaskList</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to current_user.name, user_path(current_user) %></li>
              <li><%= link_to 'Logout', logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", signup_path %></li>
              <li><%= link_to 'Log in', login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    </header>
    <div class="container">
    <%= render "layouts/flash_messages" %>
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-md-offset-2 col-sm-8 col-md-8 col-lg-offset-3 col-lg-6">
    <%= form_for(task) do |f| %>
      <% if task.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
      <%= f.label :status, 'ステータス' %> 
      <%= f.text_field :status, class: "form-control" %> </br>
      </div>
      
      <div class="form-group">
      <%= f.label :content, "タスク内容" %> </br>
      <%= f.text_field :content, class: "form-control" %>
      </div>
      
      <%= f.submit "生成" , class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> の編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>


<% if @tasks.any? %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>id</th>
      <th>Status</th>
      <th>タスク内容</th>
    </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.id, task %></td>
          <td><%= task.status %></td>
          <td><%= task.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to "新規タスク追加", new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のタスク詳細</h1>

<table class="table table-bordered">
    <tr>
      <th>id</th>
      <td> <%= @task.id %></td>
    </tr>
    
    <tr>
      <th> Status</th>
      <td> <%= @task.status %></td>
    </tr>
    
    <tr>
      <th> タスク内容</th>
      <td> <%= @task.content %></td>
    </tr>
</table>

<div class="col-sm-2">
<%= link_to "このタスクを編集する", edit_task_path(@task), class: "btn btn-default" %>
</div>
<div class="col-sm-offset-1 col-sm-1">
<%= link_to "このタスクを削除する", @message, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-danger" %></br>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class='col-md-6 col-md-offset-3'>
    <h1>タスク一覧</h1>
    

    <% if @tasks %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>id</th>
          <th>Status</th>
          <th>タスク内容</th>
        </tr>
        </thead>
        <tbody>
          <% @tasks.each do |task| %>
            <tr>
              <td><%= link_to task.id, task %></td>
              <td><%= task.status %></td>
              <td><%= task.content %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>タスク登録なし</p>
    <% end %>
    
    <%= link_to "新規タスク追加", new_task_path, class: "btn btn-primary" %>

  </div>
<% else %>
  <div class='text-center'>
    <h1>Tasklist へようこそ</h1>
    <p>試験中</p>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class = 'col-md-6 col-md-offset-3'>
  <h1>Edit form</h1>
  
  <%= form_for(@user) do |f| %>
      <div class='form-group'>
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class:'form-control' %>
      </div>
      
    <%= f.submit '変更適用', class: 'btn btn-primary btn-block' %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class='row'>
    <div class='col-md-6 col-md-offset-3'>
        <h1>Sign Up Form</h1>
        <%= form_for(@user) do |f| %>
            <div class='form-group'>
                <%= f.label :name, 'Name' %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            
            <div class='form-group'>
                <%= f.label :email, 'Email'%>
                <%= f.email_field :email, class: 'form-control' %>
            </div>
            
            <div class='form-gruop'>
                <%= f.label :password, 'Password' %>
                <%= f.password_field :password, class: 'form-control' %>
            </div>
            
          <div class="form-group">
            <%= f.label :password_confirmation, 'Confirmation' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
          <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <h2>Profile</h2>
    <h4>Name</h4>
    <p><%= @user.name %></p>
    <div id='margin_s'></div>
    <h4>Email</h4>
    <p><%= @user.email %></p>
    <div id='margin_s'></div>
    <%= link_to '登録情報を変更したい方はこちら', edit_user_path(@user) %>
  </div>
</div>